modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://github.com/Attack8/VaultHuntersJEIIntegration/issues" #optional
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
# A URL to query for updates for this mod. See the JSON update specification https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="the_vault_jei.png"
#credits="Thanks for this example mod goes to Java"
authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId="vaultadditions"
   # Optional dependency, Vault Additions has integration but is not required
   mandatory=false
   versionRange="${vault_additions_version_range}"
   ordering="NONE"
   side="BOTH"
